web:
  build: .
  ports:
    - "8080:80"
  links:
    - mysql
  volumes:
    - ~/WebProjects/elgg/:/var/www/html/
  environment:
    MYSQL_USER: root
    MYSQL_PASS: root-pass
    ELGG_USERNAME: admin
    ELGG_PASSWORD: admin-pass
    ELGG_WWW_ROOT: http://localhost:8080
mysql:
  image: mariadb:10.1  
  environment:
    MYSQL_DATABASE: elgg
    MYSQL_ROOT_PASSWORD: root-pass
